# From https://github.com/BenjaminPrice/fvtt-docker/tree/master

services:
  foundryvtt:
    image: direckthit/fvtt-docker:latest
    container_name: fvtt
    ports: 
      - 30000:30000
    volumes:
      - /path/to/your/foundry/data/directory:/data/foundryvtt
      - /path/to/your/foundry/zip/file:/host
      - /path/to/your/foundry/app/file:/opt/foundryvtt/resources/app
    restart: unless-stopped