networks:
  obsidian-livesync:
    name: obsidian-livesync
    ipam:
      config:
        - subnet: 172.38.0.0/24

services:
  couchdb:
    image: couchdb:latest
    container_name: couchdb
    user: 1000:1000
    labels:
      - deunhealth.restart.on.unhealthy=true
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    network_mode: service:gluetun
    env_file:
      - .env
    environment:
      - COUCHDB_PORT=${FIREWALL_VPN_INPUT_PORTS}
    volumes:
      - ./couchdb-data:/opt/couchdb/data
      - ./couchdb-etc:/opt/couchdb/etc/local.d
    restart: unless-stopped
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 60s
      retries: 3
      start_period: 20s
      timeout: 10s

  # We want to use AirVPN port forwaring as a reverse proxy
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      obsidian-livesync:
        ipv4_address: 172.38.0.2
    ports:
      - 0.0.0.0:${FIREWALL_VPN_INPUT_PORTS}:${FIREWALL_VPN_INPUT_PORTS} # couchdb interface
    volumes:
      - ./gluetun:/gluetun
    env_file:
      - .env
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 20s
      timeout: 10s
      retries: 5
    restart: unless-stopped